[project]
name = "sudoku-solver"
version = "0.1.0"
description = "Implementing backtrack to solve sudoku."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.10.0",
    "ruff>=0.8.4",
    "pylint>=3.3.2",
    "flake8>=7.1.1",
    "flake8-pyproject>=1.2.3",
    "mypy>=1.13.0",
    "complexipy>=1.2.0",
    "isort>=5.13.2",
    "bandit>=1.9.4",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[[tool.mypy.overrides]]
module = ""
ignore_missing_imports = true

[tool.flake8]
max-line-length = 88
ignore = ["E203", "W293"]

[tool.isort]
profile = "black"
lines_after_imports = 2
